/**
 * Safran Business Consulting - Demo Configuration & Mock Dataset
 * Toggle DEMO_ENABLED to false to hide demo access in production.
 */
export const DEMO_ENABLED = true;

import {
  UserProfile,
  Project,
  Task,
  Client,
  Invoice,
  Expense,
  Presentation,
  ChatChannel,
  ChatMessage,
  NotificationItem,
  AuditLog,
  FileItem,
  ClientNote
} from '../types';

export interface ServiceItem {
  id: string;
  name: string;
  category: string;
  description: string;
  priceTND: number;
  vatRate: number; // e.g. 19%
  deliverables: string[];
}

export const INITIAL_DEMO_USERS: UserProfile[] = [
  {
    id: 'demo_user_1',
    name: 'Dr. Karim Ben Salem',
    email: 'k.bensalem@safran-consulting.com',
    role: 'admin',
    title: 'Managing Partner & Head of Strategy',
    avatarUrl: '',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'demo_user_2',
    name: 'Amira Chahed',
    email: 'a.chahed@safran-consulting.com',
    role: 'admin',
    title: 'Partner - Corporate Finance & M&A',
    avatarUrl: '',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'demo_user_3',
    name: 'Tarek Mezghani',
    email: 't.mezghani@safran-consulting.com',
    role: 'member',
    title: 'Principal - Digital Transformation',
    avatarUrl: '',
    createdAt: '2026-02-15T11:00:00Z',
  },
  {
    id: 'demo_user_4',
    name: 'Sonia Trabelsi',
    email: 's.trabelsi@safran-consulting.com',
    role: 'member',
    title: 'Senior Operations Consultant',
    avatarUrl: '',
    createdAt: '2026-03-01T08:30:00Z',
  },
  {
    id: 'demo_user_5',
    name: 'Youssef Gharbi',
    email: 'y.gharbi@safran-consulting.com',
    role: 'member',
    title: 'Financial Modeling Specialist',
    avatarUrl: '',
    createdAt: '2026-03-10T09:45:00Z',
  },
  {
    id: 'demo_user_6',
    name: 'Ines Bouaziz',
    email: 'i.bouaziz@safran-consulting.com',
    role: 'member',
    title: 'Governance & ESG Consultant',
    avatarUrl: '',
    createdAt: '2026-04-05T14:00:00Z',
  },
  {
    id: 'demo_user_7',
    name: 'Mehdi Kallel',
    email: 'm.kallel@safran-consulting.com',
    role: 'member',
    title: 'Business Analyst',
    avatarUrl: '',
    createdAt: '2026-05-12T10:30:00Z',
  },
  {
    id: 'demo_user_8',
    name: 'Nour El Houda',
    email: 'n.elhouda@safran-consulting.com',
    role: 'member',
    title: 'Client Relations Associate',
    avatarUrl: '',
    createdAt: '2026-06-01T11:15:00Z',
  },
];

export const INITIAL_DEMO_PROJECTS: Project[] = [
  {
    id: 'proj_bank_core',
    name: 'Banque Internationale - Digital Core Modernization',
    description: '3-year digital banking core migration and operational cost restructuring.',
    color: '#9B30FF',
    status: 'active',
    createdBy: 'demo_user_1',
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'proj_retail_omni',
    name: 'Maghreb Retail Group - Omnichannel & Supply Chain',
    description: 'Procurement automation and nationwide warehouse distribution optimization.',
    color: '#FF9A1F',
    status: 'active',
    createdBy: 'demo_user_2',
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'proj_pharma_mna',
    name: 'Pharma Horizon - Corporate M&A Feasibility & Valuation',
    description: 'Buy-side commercial due diligence and DCF financial model scenario forecasting.',
    color: '#22C55E',
    status: 'active',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-01T11:00:00Z',
  },
];

export const INITIAL_DEMO_TASKS: Task[] = [
  // Project 1: Banque Internationale
  {
    id: 'task_1',
    projectId: 'proj_bank_core',
    title: 'Architecture Blueprint: Core API Gateway',
    description: 'Finalize microservices security specs with Bank CTO and infrastructure team.',
    assigneeId: 'demo_user_3',
    assigneeName: 'Tarek Mezghani',
    dueDate: '2026-10-02', // Overdue
    priority: 'high',
    status: 'todo',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'task_2',
    projectId: 'proj_bank_core',
    title: 'Vendor Benchmark: Temenos vs Thought Machine',
    description: 'Comparative functional gap analysis and license pricing matrix.',
    assigneeId: 'demo_user_7',
    assigneeName: 'Mehdi Kallel',
    dueDate: '2026-10-03', // Overdue
    priority: 'medium',
    status: 'doing',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-22T11:00:00Z',
  },
  {
    id: 'task_3',
    projectId: 'proj_bank_core',
    title: 'Executive Steering Committee Slide Deck',
    description: 'Prepare quarterly progress report and strategic roadmap milestones.',
    assigneeId: 'demo_user_1',
    assigneeName: 'Dr. Karim Ben Salem',
    dueDate: '2026-10-08',
    priority: 'high',
    status: 'doing',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-28T09:00:00Z',
  },
  {
    id: 'task_4',
    projectId: 'proj_bank_core',
    title: 'Security Compliance & Central Bank Audit',
    description: 'Ensure audit trail adheres to BCT cyber resilience directive.',
    assigneeId: 'demo_user_6',
    assigneeName: 'Ines Bouaziz',
    dueDate: '2026-10-12',
    priority: 'medium',
    status: 'todo',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-25T14:00:00Z',
  },
  {
    id: 'task_5',
    projectId: 'proj_bank_core',
    title: 'Business Requirements Document (BRD) Signoff',
    description: 'Signed off by Chief Risk Officer and Head of Retail Banking.',
    assigneeId: 'demo_user_3',
    assigneeName: 'Tarek Mezghani',
    dueDate: '2026-09-18',
    priority: 'high',
    status: 'done',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'task_6',
    projectId: 'proj_bank_core',
    title: 'Stakeholder Alignment Workshop',
    description: '30 executives aligned on target operating model milestones.',
    assigneeId: 'demo_user_1',
    assigneeName: 'Dr. Karim Ben Salem',
    dueDate: '2026-09-15',
    priority: 'medium',
    status: 'done',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    createdBy: 'demo_user_1',
    createdAt: '2026-08-20T10:00:00Z',
  },

  // Project 2: Maghreb Retail Group
  {
    id: 'task_7',
    projectId: 'proj_retail_omni',
    title: 'Warehouse Distribution Network Modeling',
    description: 'Simulate delivery times for Sousse, Sfax, and Greater Tunis hubs.',
    assigneeId: 'demo_user_4',
    assigneeName: 'Sonia Trabelsi',
    dueDate: '2026-10-04', // Overdue
    priority: 'high',
    status: 'todo',
    clientId: 'client_2',
    clientName: 'Maghreb Retail Group',
    createdBy: 'demo_user_2',
    createdAt: '2026-09-20T12:00:00Z',
  },
  {
    id: 'task_8',
    projectId: 'proj_retail_omni',
    title: 'Procurement SKU Consolidation Audit',
    description: 'Identify top 15% duplicated SKUs across 85 hypermarket locations.',
    assigneeId: 'demo_user_4',
    assigneeName: 'Sonia Trabelsi',
    dueDate: '2026-10-09',
    priority: 'medium',
    status: 'doing',
    clientId: 'client_2',
    clientName: 'Maghreb Retail Group',
    createdBy: 'demo_user_2',
    createdAt: '2026-09-24T14:30:00Z',
  },
  {
    id: 'task_9',
    projectId: 'proj_retail_omni',
    title: 'ERP & Point-of-Sale Integration Spec',
    description: 'Interface definition between SAP S/4HANA and Magento e-commerce.',
    assigneeId: 'demo_user_3',
    assigneeName: 'Tarek Mezghani',
    dueDate: '2026-10-15',
    priority: 'high',
    status: 'doing',
    clientId: 'client_2',
    clientName: 'Maghreb Retail Group',
    createdBy: 'demo_user_2',
    createdAt: '2026-09-26T16:00:00Z',
  },
  {
    id: 'task_10',
    projectId: 'proj_retail_omni',
    title: 'Supplier Contract Renegotiation Guidelines',
    description: 'Draft strategic sourcing playbooks for FMCG vendor contracts.',
    assigneeId: 'demo_user_2',
    assigneeName: 'Amira Chahed',
    dueDate: '2026-10-18',
    priority: 'low',
    status: 'todo',
    clientId: 'client_2',
    clientName: 'Maghreb Retail Group',
    createdBy: 'demo_user_2',
    createdAt: '2026-09-29T11:00:00Z',
  },
  {
    id: 'task_11',
    projectId: 'proj_retail_omni',
    title: 'Customer Journey Omnichannel Mapping',
    description: 'Click-and-collect and mobile return process flows validated.',
    assigneeId: 'demo_user_8',
    assigneeName: 'Nour El Houda',
    dueDate: '2026-09-22',
    priority: 'medium',
    status: 'done',
    clientId: 'client_2',
    clientName: 'Maghreb Retail Group',
    createdBy: 'demo_user_2',
    createdAt: '2026-09-05T09:00:00Z',
  },
  {
    id: 'task_12',
    projectId: 'proj_retail_omni',
    title: 'Supply Chain Diagnostic Baseline Report',
    description: 'Identified 3.2M TND in annual transport redundancy savings.',
    assigneeId: 'demo_user_4',
    assigneeName: 'Sonia Trabelsi',
    dueDate: '2026-09-10',
    priority: 'high',
    status: 'done',
    clientId: 'client_2',
    clientName: 'Maghreb Retail Group',
    createdBy: 'demo_user_2',
    createdAt: '2026-08-25T11:00:00Z',
  },

  // Project 3: Pharma Horizon
  {
    id: 'task_13',
    projectId: 'proj_pharma_mna',
    title: 'DCF 10-Year Valuation Model',
    description: 'Sensitivity analysis on patent expiration and generic pipeline entry.',
    assigneeId: 'demo_user_5',
    assigneeName: 'Youssef Gharbi',
    dueDate: '2026-10-01', // Overdue
    priority: 'high',
    status: 'doing',
    clientId: 'client_3',
    clientName: 'Laboratoires Pharma Horizon',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'task_14',
    projectId: 'proj_pharma_mna',
    title: 'Regulatory Due Diligence Dossier',
    description: 'Review DPM drug registration status and EMA export certifications.',
    assigneeId: 'demo_user_6',
    assigneeName: 'Ines Bouaziz',
    dueDate: '2026-10-07',
    priority: 'medium',
    status: 'todo',
    clientId: 'client_3',
    clientName: 'Laboratoires Pharma Horizon',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-27T10:00:00Z',
  },
  {
    id: 'task_15',
    projectId: 'proj_pharma_mna',
    title: 'Quality & GMP Plant Audit Inspection',
    description: 'On-site technical evaluation of the Zaghouan manufacturing facility.',
    assigneeId: 'demo_user_4',
    assigneeName: 'Sonia Trabelsi',
    dueDate: '2026-10-10',
    priority: 'high',
    status: 'todo',
    clientId: 'client_3',
    clientName: 'Laboratoires Pharma Horizon',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-28T14:00:00Z',
  },
  {
    id: 'task_16',
    projectId: 'proj_pharma_mna',
    title: 'Synergy Valuation & Cost Elimination Memo',
    description: 'Projected 4.8M TND in SG&A synergies post-acquisition.',
    assigneeId: 'demo_user_5',
    assigneeName: 'Youssef Gharbi',
    dueDate: '2026-10-16',
    priority: 'high',
    status: 'todo',
    clientId: 'client_3',
    clientName: 'Laboratoires Pharma Horizon',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-30T15:00:00Z',
  },
  {
    id: 'task_17',
    projectId: 'proj_pharma_mna',
    title: 'Teaser & Information Memorandum (CIM)',
    description: 'Approved by board for selective dissemination to qualified buyers.',
    assigneeId: 'demo_user_2',
    assigneeName: 'Amira Chahed',
    dueDate: '2026-09-20',
    priority: 'high',
    status: 'done',
    clientId: 'client_3',
    clientName: 'Laboratoires Pharma Horizon',
    createdBy: 'demo_user_1',
    createdAt: '2026-09-02T11:00:00Z',
  },
  {
    id: 'task_18',
    projectId: 'proj_pharma_mna',
    title: 'Virtual Data Room (VDR) Indexing',
    description: 'Clean room established with confidentiality agreements countersigned.',
    assigneeId: 'demo_user_7',
    assigneeName: 'Mehdi Kallel',
    dueDate: '2026-09-12',
    priority: 'low',
    status: 'done',
    clientId: 'client_3',
    clientName: 'Laboratoires Pharma Horizon',
    createdBy: 'demo_user_1',
    createdAt: '2026-08-28T09:00:00Z',
  },
];

export const INITIAL_DEMO_CLIENTS: Client[] = [
  {
    id: 'client_1',
    name: 'Banque Internationale de Tunis',
    company: 'BIT Group Finance',
    email: 'direction.generale@bit-finance.tn',
    phone: '+216 71 840 000',
    status: 'active',
    notes: 'Key banking client. Currently modernizing retail core and online banking apps.',
    ownerId: 'demo_user_1',
    ownerName: 'Dr. Karim Ben Salem',
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'client_2',
    name: 'Maghreb Retail Group',
    company: 'MRG Supermarkets & Logistics',
    email: 'contact@mrg-retail.com',
    phone: '+216 70 120 500',
    status: 'active',
    notes: '85 locations nationwide. Implementing unified supply chain and e-commerce fulfillment.',
    ownerId: 'demo_user_2',
    ownerName: 'Amira Chahed',
    createdAt: '2026-02-10T11:00:00Z',
  },
  {
    id: 'client_3',
    name: 'Laboratoires Pharma Horizon',
    company: 'Horizon Pharmaceuticals SA',
    email: 'mna@horizon-pharma.tn',
    phone: '+216 72 450 800',
    status: 'active',
    notes: 'Leading sterile injectable manufacturer exploring strategic minority acquisition.',
    ownerId: 'demo_user_1',
    ownerName: 'Dr. Karim Ben Salem',
    createdAt: '2026-03-05T09:30:00Z',
  },
  {
    id: 'client_4',
    name: 'Tunis Telecom Infra',
    company: 'TT Fiber Network Holdings',
    email: 'infra.strategy@tt-infra.tn',
    phone: '+216 71 900 120',
    status: 'active',
    notes: 'Telecom towers carved-out entity. Advising on 5G fiber co-investment model.',
    ownerId: 'demo_user_3',
    ownerName: 'Tarek Mezghani',
    createdAt: '2026-03-18T14:00:00Z',
  },
  {
    id: 'client_5',
    name: 'Stafim Automotive Distribution',
    company: 'Stafim Mobility Services',
    email: 'executive@stafim-auto.tn',
    phone: '+216 71 330 400',
    status: 'lead',
    notes: 'Proposal submitted for electric vehicle (EV) charging network economic feasibility.',
    ownerId: 'demo_user_4',
    ownerName: 'Sonia Trabelsi',
    createdAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'client_6',
    name: 'Carthage Cement & Minerals',
    company: 'Carthage Industrial Group',
    email: 'audit@carthage-cement.tn',
    phone: '+216 79 390 200',
    status: 'lead',
    notes: 'Exploring energy transition & carbon credit compliance advisory.',
    ownerId: 'demo_user_6',
    ownerName: 'Ines Bouaziz',
    createdAt: '2026-08-22T11:00:00Z',
  },
  {
    id: 'client_7',
    name: 'AfricInvest Private Equity',
    company: 'AfricInvest Capital Partners',
    email: 'portfolio@africinvest.com',
    phone: '+216 71 189 000',
    status: 'active',
    notes: 'Regular commercial due diligence partner for Maghreb and West Africa investments.',
    ownerId: 'demo_user_2',
    ownerName: 'Amira Chahed',
    createdAt: '2026-04-12T09:00:00Z',
  },
  {
    id: 'client_8',
    name: 'Monoprix Tunisia Distribution',
    company: 'SNMVT Monoprix',
    email: 'cfo@monoprix.tn',
    phone: '+216 71 144 000',
    status: 'closed',
    notes: 'Completed inventory turnover optimization engagement with 18% holding cost reduction.',
    ownerId: 'demo_user_4',
    ownerName: 'Sonia Trabelsi',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'client_9',
    name: 'Attijari Leasing Corp',
    company: 'Attijariwafa Group',
    email: 'contact@attijarileasing.com.tn',
    phone: '+216 71 860 300',
    status: 'lead',
    notes: 'Introductory discussion for SME digital underwriting scorecards.',
    ownerId: 'demo_user_5',
    ownerName: 'Youssef Gharbi',
    createdAt: '2026-09-10T15:00:00Z',
  },
  {
    id: 'client_10',
    name: 'Groupe Délice Danone',
    company: 'Société Tunisienne de Boissons',
    email: 'supplychain@delice.tn',
    phone: '+216 71 430 000',
    status: 'closed',
    notes: 'Cold chain route-to-market rationalization completed with flying colors.',
    ownerId: 'demo_user_4',
    ownerName: 'Sonia Trabelsi',
    createdAt: '2026-02-14T08:00:00Z',
  },
  {
    id: 'client_11',
    name: 'BIAT Assurances',
    company: 'Banque Internationale Arabe de Tunisie',
    email: 'direction@biatassurances.tn',
    phone: '+216 71 340 777',
    status: 'active',
    notes: 'Bancassurance omnichannel sales funnel restructuring and agent incentive design.',
    ownerId: 'demo_user_1',
    ownerName: 'Dr. Karim Ben Salem',
    createdAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'client_12',
    name: 'SOTETEL Telecommunications',
    company: 'SOTETEL SA',
    email: 'strategy@sotetel.tn',
    phone: '+216 71 960 555',
    status: 'lead',
    notes: 'Smart cities and IoT commercial strategy proposal under executive evaluation.',
    ownerId: 'demo_user_3',
    ownerName: 'Tarek Mezghani',
    createdAt: '2026-09-18T11:00:00Z',
  },
];

export const INITIAL_DEMO_SERVICES: ServiceItem[] = [
  {
    id: 'srv_1',
    name: 'Enterprise Strategic Roadmap & Vision 2030',
    category: 'Strategic Advisory',
    description: 'Full corporate restructuring, market positioning, and 5-year financial planning.',
    priceTND: 45000,
    vatRate: 0.19,
    deliverables: ['Executive Board Deck', 'Financial Scenario Matrix', 'Implementation Playbook'],
  },
  {
    id: 'srv_2',
    name: 'Commercial & Financial Due Diligence (Buy-Side)',
    category: 'Corporate Finance & M&A',
    description: 'Rigorous target company balance sheet, earnings quality, and customer retention audit.',
    priceTND: 38000,
    vatRate: 0.19,
    deliverables: ['Quality of Earnings (QoE) Report', 'DCF Valuation Model', 'Red Flag Risk Dossier'],
  },
  {
    id: 'srv_3',
    name: 'Digital Transformation & Core System Migration',
    category: 'Digital & Technology',
    description: 'Target architecture design, cloud vendor selection, and agile PMO governance.',
    priceTND: 32000,
    vatRate: 0.19,
    deliverables: ['Microservices Architecture Blueprint', 'Vendor RFP Scorecard', 'Migration Timetable'],
  },
  {
    id: 'srv_4',
    name: 'Supply Chain & Logistics Network Optimization',
    category: 'Operations Advisory',
    description: 'Warehouse layout modeling, fleet routing, and supplier procurement cost takeout.',
    priceTND: 28000,
    vatRate: 0.19,
    deliverables: ['Logistics Network Simulation', 'Procurement Savings Tracker', 'SOP Manual'],
  },
  {
    id: 'srv_5',
    name: 'Corporate Governance & Risk Architecture (ERM)',
    category: 'Compliance & Governance',
    description: 'Board committee charters, internal controls, regulatory compliance, and risk registers.',
    priceTND: 22000,
    vatRate: 0.19,
    deliverables: ['Enterprise Risk Matrix', 'Audit Committee Charter', 'Compliance Audit Report'],
  },
  {
    id: 'srv_6',
    name: 'Executive Leadership Alignment & Change Management',
    category: 'Organizational Development',
    description: 'Stakeholder interviews, change readiness assessment, and incentive compensation design.',
    priceTND: 18500,
    vatRate: 0.19,
    deliverables: ['Executive Alignment Synthesis', 'Communication Cascade Plan', 'KPI Scorecard'],
  },
  {
    id: 'srv_7',
    name: 'Customer Experience & Omnichannel Journey Blueprint',
    category: 'Commercial & Marketing',
    description: 'Voice of customer research, friction audit, and digital touchpoint redesign.',
    priceTND: 16000,
    vatRate: 0.19,
    deliverables: ['Customer Journey Map', 'Service Blueprint', 'NPS Improvement Roadmap'],
  },
  {
    id: 'srv_8',
    name: 'Financial Modeling & Capital Restructuring Advisory',
    category: 'Corporate Finance & M&A',
    description: 'Debt refinancing feasibility, working capital optimization, and covenant monitoring.',
    priceTND: 26000,
    vatRate: 0.19,
    deliverables: ['Dynamic 3-Statement Model', 'Debt Capacity Memo', 'Liquidity Forecast'],
  },
  {
    id: 'srv_9',
    name: 'ESG Strategy, Decarbonization & CSRD Alignment',
    category: 'Sustainability',
    description: 'Carbon baseline footprint, circular economy feasibility, and green financing readiness.',
    priceTND: 24000,
    vatRate: 0.19,
    deliverables: ['ESG Materiality Matrix', 'Decarbonization Roadmap', 'Green Bond Framework'],
  },
  {
    id: 'srv_10',
    name: 'Post-Merger Integration (PMI) Day-1 Execution',
    category: 'Corporate Finance & M&A',
    description: 'Integration management office (IMO) leadership, culture fusion, and synergy realization.',
    priceTND: 42000,
    vatRate: 0.19,
    deliverables: ['100-Day Integration Plan', 'Synergy Realization Dashboard', 'Culture Survey Report'],
  },
];

export const INITIAL_DEMO_INVOICES: Invoice[] = [
  {
    id: 'inv_demo_1',
    invoiceNumber: 'SBC-2026-001',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    clientCompany: 'BIT Group Finance',
    clientEmail: 'direction.generale@bit-finance.tn',
    date: '2026-08-15',
    dueDate: '2026-09-15',
    status: 'paid',
    lineItems: [
      { id: '1', description: 'Phase 1: Digital Core Modernization Diagnostic', quantity: 1, unitPrice: 35000, total: 35000 },
      { id: '2', description: 'Central Bank Regulatory Risk Assessment', quantity: 1, unitPrice: 12000, total: 12000 },
    ],
    subtotal: 47000,
    taxPercent: 19,
    taxAmount: 8930,
    discountPercent: 0,
    discountAmount: 0,
    total: 55930,
    notes: 'Settled via BIAT wire transfer ref: #WT-88291. Thank you for your partnership.',
    createdBy: 'demo_user_1',
    createdByName: 'Dr. Karim Ben Salem',
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'inv_demo_2',
    invoiceNumber: 'SBC-2026-002',
    clientId: 'client_2',
    clientName: 'Maghreb Retail Group',
    clientCompany: 'MRG Supermarkets & Logistics',
    clientEmail: 'contact@mrg-retail.com',
    date: '2026-08-28',
    dueDate: '2026-09-28',
    status: 'paid',
    lineItems: [
      { id: '1', description: 'Supply Chain Diagnostic & Hub Simulation', quantity: 1, unitPrice: 28000, total: 28000 },
      { id: '2', description: 'Inventory Holding Cost Reduction Advisory', quantity: 1, unitPrice: 15000, total: 15000 },
    ],
    subtotal: 43000,
    taxPercent: 19,
    taxAmount: 8170,
    discountPercent: 5,
    discountAmount: 2150,
    total: 49020,
    notes: 'Settled via bank check. Early payment discount of 5% applied.',
    createdBy: 'demo_user_2',
    createdByName: 'Amira Chahed',
    createdAt: '2026-08-28T14:00:00Z',
  },
  {
    id: 'inv_demo_3',
    invoiceNumber: 'SBC-2026-003',
    clientId: 'client_3',
    clientName: 'Laboratoires Pharma Horizon',
    clientCompany: 'Horizon Pharmaceuticals SA',
    clientEmail: 'mna@horizon-pharma.tn',
    date: '2026-09-01',
    dueDate: '2026-09-25', // Overdue
    status: 'overdue',
    lineItems: [
      { id: '1', description: 'Buy-Side Commercial Due Diligence Report', quantity: 1, unitPrice: 38000, total: 38000 },
      { id: '2', description: 'DCF 10-Year Scenario Valuation Model', quantity: 1, unitPrice: 26000, total: 26000 },
    ],
    subtotal: 64000,
    taxPercent: 19,
    taxAmount: 12160,
    discountPercent: 0,
    discountAmount: 0,
    total: 76160,
    notes: 'Payment reminder sent on Oct 2nd. Awaiting CFO final disbursement clearance.',
    createdBy: 'demo_user_1',
    createdByName: 'Dr. Karim Ben Salem',
    createdAt: '2026-09-01T09:00:00Z',
  },
  {
    id: 'inv_demo_4',
    invoiceNumber: 'SBC-2026-004',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    clientCompany: 'BIT Group Finance',
    clientEmail: 'direction.generale@bit-finance.tn',
    date: '2026-09-15',
    dueDate: '2026-10-15',
    status: 'sent',
    lineItems: [
      { id: '1', description: 'Phase 2: Microservices Architecture Blueprint', quantity: 1, unitPrice: 32000, total: 32000 },
      { id: '2', description: 'Vendor Selection RFP Evaluation Services', quantity: 1, unitPrice: 18000, total: 18000 },
    ],
    subtotal: 50000,
    taxPercent: 19,
    taxAmount: 9500,
    discountPercent: 0,
    discountAmount: 0,
    total: 59500,
    notes: 'Milestone 2 deliverable invoice. Net 30 days.',
    createdBy: 'demo_user_1',
    createdByName: 'Dr. Karim Ben Salem',
    createdAt: '2026-09-15T11:00:00Z',
  },
  {
    id: 'inv_demo_5',
    invoiceNumber: 'SBC-2026-005',
    clientId: 'client_7',
    clientName: 'AfricInvest Private Equity',
    clientCompany: 'AfricInvest Capital Partners',
    clientEmail: 'portfolio@africinvest.com',
    date: '2026-09-20',
    dueDate: '2026-10-20',
    status: 'sent',
    lineItems: [
      { id: '1', description: 'Financial & Market Due Diligence - Fintech Target', quantity: 1, unitPrice: 28000, total: 28000 },
    ],
    subtotal: 28000,
    taxPercent: 19,
    taxAmount: 5320,
    discountPercent: 0,
    discountAmount: 0,
    total: 33320,
    notes: 'Confidential target evaluation. Deliverable accepted by investment committee.',
    createdBy: 'demo_user_2',
    createdByName: 'Amira Chahed',
    createdAt: '2026-09-20T16:00:00Z',
  },
  {
    id: 'inv_demo_6',
    invoiceNumber: 'SBC-2026-006',
    clientId: 'client_4',
    clientName: 'Tunis Telecom Infra',
    clientCompany: 'TT Fiber Network Holdings',
    clientEmail: 'infra.strategy@tt-infra.tn',
    date: '2026-09-28',
    dueDate: '2026-10-28',
    status: 'draft',
    lineItems: [
      { id: '1', description: '5G Fiber Co-Investment Economic Feasibility', quantity: 1, unitPrice: 22000, total: 22000 },
      { id: '2', description: 'Tower Sharing Regulatory Review Memo', quantity: 1, unitPrice: 11000, total: 11000 },
    ],
    subtotal: 33000,
    taxPercent: 19,
    taxAmount: 6270,
    discountPercent: 0,
    discountAmount: 0,
    total: 39270,
    notes: 'Draft awaiting partner review before delivery to client.',
    createdBy: 'demo_user_3',
    createdByName: 'Tarek Mezghani',
    createdAt: '2026-09-28T09:30:00Z',
  },
  {
    id: 'inv_demo_7',
    invoiceNumber: 'SBC-2026-007',
    clientId: 'client_11',
    clientName: 'BIAT Assurances',
    clientCompany: 'Banque Internationale Arabe de Tunisie',
    clientEmail: 'direction@biatassurances.tn',
    date: '2026-09-10',
    dueDate: '2026-09-30', // Overdue
    status: 'overdue',
    lineItems: [
      { id: '1', description: 'Bancassurance Sales Funnel Restructuring', quantity: 1, unitPrice: 19000, total: 19000 },
    ],
    subtotal: 19000,
    taxPercent: 19,
    taxAmount: 3610,
    discountPercent: 0,
    discountAmount: 0,
    total: 22610,
    notes: 'Payment scheduled for early next week.',
    createdBy: 'demo_user_1',
    createdByName: 'Dr. Karim Ben Salem',
    createdAt: '2026-09-10T14:00:00Z',
  },
  {
    id: 'inv_demo_8',
    invoiceNumber: 'SBC-2026-008',
    clientId: 'client_8',
    clientName: 'Monoprix Tunisia Distribution',
    clientCompany: 'SNMVT Monoprix',
    clientEmail: 'cfo@monoprix.tn',
    date: '2026-07-20',
    dueDate: '2026-08-20',
    status: 'paid',
    lineItems: [
      { id: '1', description: 'Store Inventory Holding Cost Optimization', quantity: 1, unitPrice: 24000, total: 24000 },
    ],
    subtotal: 24000,
    taxPercent: 19,
    taxAmount: 4560,
    discountPercent: 0,
    discountAmount: 0,
    total: 28560,
    notes: 'Fully settled. Final delivery certificate signed.',
    createdBy: 'demo_user_4',
    createdByName: 'Sonia Trabelsi',
    createdAt: '2026-07-20T10:00:00Z',
  },
];

export const INITIAL_DEMO_EXPENSES: Expense[] = [
  {
    id: 'exp_1',
    description: 'Bloomberg Professional Terminal License (Q3)',
    amount: 14800,
    category: 'Software',
    date: '2026-08-01',
    recordedBy: 'demo_user_1',
    recorderName: 'Dr. Karim Ben Salem',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'exp_2',
    description: 'Expert Technical Auditor - Cloud Core Architecture',
    amount: 9500,
    category: 'Contractor',
    date: '2026-08-15',
    projectId: 'proj_bank_core',
    projectName: 'Banque Internationale - Digital Core Modernization',
    recordedBy: 'demo_user_3',
    recorderName: 'Tarek Mezghani',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'exp_3',
    description: 'Executive Travel & Client Workshops - Paris & Lyon',
    amount: 5200,
    category: 'Travel',
    date: '2026-08-22',
    recordedBy: 'demo_user_1',
    recorderName: 'Dr. Karim Ben Salem',
    createdAt: '2026-08-22T10:00:00Z',
  },
  {
    id: 'exp_4',
    description: 'Corporate Legal Advisory & Regulatory Filing Support',
    amount: 7400,
    category: 'Legal',
    date: '2026-09-05',
    recordedBy: 'demo_user_2',
    recorderName: 'Amira Chahed',
    createdAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'exp_5',
    description: 'Gartner Industry Intelligence & IT Research Subscription',
    amount: 8600,
    category: 'Software',
    date: '2026-09-12',
    recordedBy: 'demo_user_1',
    recorderName: 'Dr. Karim Ben Salem',
    createdAt: '2026-09-12T11:00:00Z',
  },
];

export const INITIAL_DEMO_PRESENTATIONS: Presentation[] = [
  {
    id: 'pres_1',
    title: 'Banque Internationale: Strategic Digital Core Transformation',
    description: 'Executive pitch deck presented to the Board of Directors detailing architecture modernization.',
    category: 'Clients',
    type: 'pdf',
    version: 2,
    slideCount: 12,
    tags: ['banking', 'fintech', 'strategy'],
    uploadedBy: 'demo_user_1',
    uploaderName: 'Dr. Karim Ben Salem',
    fileUrl: 'data:application/pdf;base64,JVBERi0xLjQKJ',
    createdAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'pres_2',
    title: 'Safran Business Consulting - Corporate Capabilities & Credentials 2026',
    description: 'Interactive Canva presentation showcasing our advisory practices and client success stories.',
    category: 'Proposals',
    type: 'canva',
    canvaUrl: 'https://www.canva.com/design/DAFexample/view',
    version: 3,
    slideCount: 16,
    tags: ['credentials', 'capabilities', 'firm'],
    uploadedBy: 'demo_user_1',
    uploaderName: 'Dr. Karim Ben Salem',
    createdAt: '2026-08-10T14:00:00Z',
  },
  {
    id: 'pres_3',
    title: 'Pharma Horizon M&A Due Diligence & Valuation Synthesis',
    description: 'Comprehensive buy-side valuation analysis, DCF modeling, and synergy realization timeline.',
    category: 'Clients',
    type: 'pdf',
    version: 1,
    slideCount: 10,
    tags: ['mna', 'pharma', 'valuation'],
    uploadedBy: 'demo_user_2',
    uploaderName: 'Amira Chahed',
    fileUrl: 'data:application/pdf;base64,JVBERi0xLjQKJ',
    createdAt: '2026-09-25T11:00:00Z',
  },
  {
    id: 'pres_4',
    title: 'Consulting Methodology & Problem-Solving Framework',
    description: 'Internal consultant training slides on MECE structuring, hypothesis testing, and executive storytelling.',
    category: 'Training',
    type: 'pptx',
    version: 1,
    slideCount: 14,
    tags: ['training', 'onboarding', 'frameworks'],
    uploadedBy: 'demo_user_1',
    uploaderName: 'Dr. Karim Ben Salem',
    createdAt: '2026-07-15T09:00:00Z',
  },
  {
    id: 'pres_5',
    title: 'Maghreb Retail Group - Omnichannel Supply Chain Blueprint',
    description: 'Store inventory rationalization, automated warehouse hubs, and delivery route simulation.',
    category: 'Clients',
    type: 'pdf',
    version: 2,
    slideCount: 8,
    tags: ['retail', 'logistics', 'supplychain'],
    uploadedBy: 'demo_user_4',
    uploaderName: 'Sonia Trabelsi',
    fileUrl: 'data:application/pdf;base64,JVBERi0xLjQKJ',
    createdAt: '2026-09-18T16:00:00Z',
  },
];

export const INITIAL_DEMO_CHANNELS: ChatChannel[] = [
  {
    id: 'general',
    name: 'General Advisory Practice',
    type: 'general',
    lastMessage: 'All team members please review Q4 capacity allocation.',
    lastMessageAt: '2026-10-05T14:30:00Z',
    unreadCount: 2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'proj_bank_core',
    name: 'Banque Internationale Core',
    type: 'project',
    projectId: 'proj_bank_core',
    lastMessage: 'Steering committee presentation slides approved by client.',
    lastMessageAt: '2026-10-05T16:15:00Z',
    unreadCount: 1,
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'proj_retail_omni',
    name: 'Retail Group Supply Chain',
    type: 'project',
    projectId: 'proj_retail_omni',
    lastMessage: 'Logistics simulation results uploaded to the Files vault.',
    lastMessageAt: '2026-10-04T18:00:00Z',
    unreadCount: 0,
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'proj_pharma_mna',
    name: 'Pharma Horizon M&A',
    type: 'project',
    projectId: 'proj_pharma_mna',
    lastMessage: 'VDR audit room is fully synced with bidder NDA forms.',
    lastMessageAt: '2026-10-05T11:20:00Z',
    unreadCount: 0,
    createdAt: '2026-09-01T11:00:00Z',
  },
];

export const INITIAL_DEMO_MESSAGES: Record<string, ChatMessage[]> = {
  general: [
    {
      id: 'msg_1',
      channelId: 'general',
      senderId: 'demo_user_1',
      senderName: 'Dr. Karim Ben Salem',
      content: 'Welcome team! Excellent performance across all Q3 advisory deliverables.',
      createdAt: '2026-10-05T09:00:00Z',
    },
    {
      id: 'msg_2',
      channelId: 'general',
      senderId: 'demo_user_2',
      senderName: 'Amira Chahed',
      content: 'Reminder that all client invoices for September have been issued and synced.',
      createdAt: '2026-10-05T11:15:00Z',
    },
    {
      id: 'msg_3',
      channelId: 'general',
      senderId: 'demo_user_3',
      senderName: 'Tarek Mezghani',
      content: 'All team members please review Q4 capacity allocation in the task boards.',
      createdAt: '2026-10-05T14:30:00Z',
    },
  ],
  proj_bank_core: [
    {
      id: 'msg_bc_1',
      channelId: 'proj_bank_core',
      senderId: 'demo_user_3',
      senderName: 'Tarek Mezghani',
      content: 'Architecture blueprint review with the bank CTO went exceptionally well.',
      createdAt: '2026-10-05T15:00:00Z',
    },
    {
      id: 'msg_bc_2',
      channelId: 'proj_bank_core',
      senderId: 'demo_user_1',
      senderName: 'Dr. Karim Ben Salem',
      content: 'Steering committee presentation slides approved by client.',
      createdAt: '2026-10-05T16:15:00Z',
    },
  ],
};

export const INITIAL_DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'demo_user_1',
    title: 'Client Payment Received',
    message: 'Banque Internationale settled invoice #SBC-2026-001 (55,930 TND).',
    type: 'invoice',
    read: false,
    createdAt: '2026-10-05T15:45:00Z',
  },
  {
    id: 'notif_2',
    userId: 'demo_user_1',
    title: 'High Priority Task Due Today',
    message: 'Architecture Blueprint: Core API Gateway due date is today.',
    type: 'task',
    read: false,
    createdAt: '2026-10-05T10:00:00Z',
  },
  {
    id: 'notif_3',
    userId: 'demo_user_1',
    title: 'New Deck Uploaded',
    message: 'Amira Chahed uploaded a new version of Pharma Horizon M&A deck.',
    type: 'system',
    read: true,
    createdAt: '2026-10-04T17:20:00Z',
  },
];

export const INITIAL_DEMO_FILES: FileItem[] = [
  {
    id: 'file_1',
    name: 'Banque_Internationale_Core_API_Architecture_v2.pdf',
    size: 4200000,
    type: 'application/pdf',
    folder: 'Documents',
    projectId: 'proj_bank_core',
    projectName: 'Banque Internationale - Digital Core Modernization',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    url: 'https://example.com/files/bank_core_arch.pdf',
    uploadedBy: 'demo_user_3',
    uploaderName: 'Tarek Mezghani',
    createdAt: '2026-09-22T14:30:00Z',
  },
  {
    id: 'file_2',
    name: 'Pharma_Horizon_Commercial_Due_Diligence_Report.pdf',
    size: 8500000,
    type: 'application/pdf',
    folder: 'Documents',
    projectId: 'proj_pharma_mna',
    projectName: 'Pharma Horizon - Corporate M&A Feasibility & Valuation',
    clientId: 'client_3',
    clientName: 'Laboratoires Pharma Horizon',
    url: 'https://example.com/files/pharma_dd.pdf',
    uploadedBy: 'demo_user_2',
    uploaderName: 'Amira Chahed',
    createdAt: '2026-09-25T11:00:00Z',
  },
  {
    id: 'file_3',
    name: 'Maghreb_Retail_Supply_Chain_Simulation.xlsx',
    size: 2400000,
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    folder: 'Design',
    projectId: 'proj_retail_omni',
    projectName: 'Maghreb Retail Group - Omnichannel & Supply Chain',
    clientId: 'client_2',
    clientName: 'Maghreb Retail Group',
    url: 'https://example.com/files/retail_logistics.xlsx',
    uploadedBy: 'demo_user_4',
    uploaderName: 'Sonia Trabelsi',
    createdAt: '2026-09-28T16:00:00Z',
  },
  {
    id: 'file_4',
    name: 'Safran_Master_Advisory_Engagement_Agreement_2026.pdf',
    size: 1850000,
    type: 'application/pdf',
    folder: 'Contracts',
    clientId: 'client_1',
    clientName: 'Banque Internationale de Tunis',
    url: 'https://example.com/files/master_agreement.pdf',
    uploadedBy: 'demo_user_1',
    uploaderName: 'Dr. Karim Ben Salem',
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'file_5',
    name: 'Tunis_Telecom_5G_Fiber_Feasibility_Study.pdf',
    size: 3600000,
    type: 'application/pdf',
    folder: 'Proposals',
    clientId: 'client_4',
    clientName: 'Tunis Telecom Infra',
    url: 'https://example.com/files/tt_5g_fiber.pdf',
    uploadedBy: 'demo_user_3',
    uploaderName: 'Tarek Mezghani',
    createdAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'file_6',
    name: 'Consulting_Code_of_Ethics_and_Compliance_SBC.pdf',
    size: 1100000,
    type: 'application/pdf',
    folder: 'General',
    url: 'https://example.com/files/ethics_code.pdf',
    uploadedBy: 'demo_user_1',
    uploaderName: 'Dr. Karim Ben Salem',
    createdAt: '2026-07-01T08:00:00Z',
  },
];

export const INITIAL_DEMO_NOTES: Record<string, ClientNote[]> = {
  client_1: [
    {
      id: 'note_c1_1',
      clientId: 'client_1',
      content: 'Board of Directors confirmed the Q4 steering committee date. Microservices gateway architecture endorsed unanimously.',
      authorId: 'demo_user_1',
      authorName: 'Dr. Karim Ben Salem',
      createdAt: '2026-10-02T14:00:00Z',
    },
    {
      id: 'note_c1_2',
      clientId: 'client_1',
      content: 'Central Bank compliance audit review meeting scheduled for next Tuesday with Chief Risk Officer.',
      authorId: 'demo_user_3',
      authorName: 'Tarek Mezghani',
      createdAt: '2026-09-24T11:30:00Z',
    },
  ],
  client_2: [
    {
      id: 'note_c2_1',
      clientId: 'client_2',
      content: 'Identified 3.2M TND potential savings in transport route consolidation across Greater Tunis and Sfax regional hubs.',
      authorId: 'demo_user_4',
      authorName: 'Sonia Trabelsi',
      createdAt: '2026-09-28T16:15:00Z',
    },
  ],
  client_3: [
    {
      id: 'note_c3_1',
      clientId: 'client_3',
      content: 'Virtual Data Room (VDR) is 100% indexed. Three qualified pharmaceutical suitors have signed confidentiality NDAs.',
      authorId: 'demo_user_2',
      authorName: 'Amira Chahed',
      createdAt: '2026-09-30T10:20:00Z',
    },
  ],
  client_4: [
    {
      id: 'note_c4_1',
      clientId: 'client_4',
      content: 'Draft co-investment model prepared for fiber backbone expansion. Awaiting regulatory feedback.',
      authorId: 'demo_user_3',
      authorName: 'Tarek Mezghani',
      createdAt: '2026-09-18T15:00:00Z',
    },
  ],
};
